apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: github-action
  name: nginx-server
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        resources:
          limits:
            cpu: '0.25'
            memory: '128M'
        ports:
        - containerPort: 80
